# Generated by Django 3.2.6 on 2022-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20220116_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
    ]
