# Generated by Django 3.2.6 on 2022-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_answer_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answerCount',
            field=models.IntegerField(default=0),
        ),
    ]
