# Generated by Django 3.2.6 on 2022-02-20 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
